apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090/prometheus
    access: proxy
    basicAuth: false
    version: 1
    editable: false
    